# Common dev profile configuration
spring.application.name=global-config
spring.profiles.active=dev

# Example common property for all services
app.message=Hello from Global Config (DEV profile)

# Common logging level
logging.level.root=INFO
#logging.level.com.example=DEBUG
