spring.application.name=payment-service


# Schema
spring.jpa.properties.hibernate.default_schema=payment

# SERVER PORT (optional)
server.port=8085
management.endpoints.web.exposure.include=*

#later will use
spring.cloud.config.enabled=false
#spring.cloud.import-check.enabled=false
